"""UI text in French, English and Arabic, plus the language cycle order used
by the header's language-switch button."""

LANG_ORDER = ["fr", "en", "ar"]

TEXTS = {
    "fr": {
        "flag_path": "assets/flags/fr.png",
        "app_title": "DXF Tool",
        "files_zone": "FICHIERS",
        "add_files": "Déposer des fichiers DXF",
        "total": "Total",
        "traitement": "Traitement",
        "plies_count": "Nombre de plis",
        "patch_tested": "Patchs testés",
        "patch_valid": "Patchs valides",
        "surface": "Surface exploitable",
        "unusable_surface": "Surface inexploitable",
        "percent": "Pourcentage exploitable",
        "estimated_mass": "Masse estimée",
        "areal_mass": "Masse surfacique (g/m²)",
        "main_zone": "RÉSULTATS",
        "binary": "Vue binaire",
        "gradient": "Vue dégradée",
        "chips_export": "Exporter le DXF avec les chips",
        "click_file": "Sélectionnez un fichier pour voir son analyse.",
    },
    "en": {
        "flag_path": "assets/flags/en.png",
        "app_title": "DXF Tool",
        "files_zone": "FILES",
        "add_files": "Drop DXF files",
        "total": "Total",
        "traitement": "Processing",
        "plies_count": "Number of plies",
        "patch_tested": "Patches tested",
        "patch_valid": "Valid patches",
        "surface": "Usable surface",
        "unusable_surface": "Unusable surface",
        "percent": "Usable percentage",
        "estimated_mass": "Estimated mass",
        "areal_mass": "Areal mass (g/m²)",
        "main_zone": "RESULTS",
        "binary": "Binary view",
        "gradient": "Gradient view",
        "chips_export": "Export DXF with chips",
        "click_file": "Select a file to see its analysis.",
    },
    "ar": {
        "flag_path": "assets/flags/ar.png",
        "app_title": "أداة DXF",
        "files_zone": "الملفات",
        "add_files": "أفلت ملفات DXF",
        "total": "الإجمالي",
        "traitement": "المعالجة",
        "plies_count": "عدد الطبقات",
        "patch_tested": "الرقع المختبرة",
        "patch_valid": "الرقع الصالحة",
        "surface": "المساحة القابلة للاستخدام",
        "unusable_surface": "المساحة غير القابلة للاستخدام",
        "percent": "النسبة القابلة للاستخدام",
        "estimated_mass": "الكتلة المقدرة",
        "areal_mass": "الكتلة السطحية (غ/م²)",
        "main_zone": "النتائج",
        "binary": "عرض ثنائي",
        "gradient": "عرض متدرج",
        "chips_export": "تصدير DXF مع الرقع",
        "click_file": "اختر ملفًا لعرض تحليله.",
    },
}
